-- Auto-generated by scripts/_generate-orphan-skus.mjs on 2026-05-02.
-- 38 new SKU(s) for orphan images.
-- variant_group + variant_type derived automatically by the
-- skus_derive_variant_trigger from migration 0013.

insert into skus (slug, year, brand, sport, set_name, product, release_date, description, image_url, gradient_from, gradient_to)
values
  ('2024-25-panini-donruss-basketball-hobby-box', 2024, 'Panini', 'NBA', 'Donruss', 'Hobby Box', '2025-02-15', '2024-25 Panini Donruss NBA Hobby Box.', '/products/2024-25-panini-donruss-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2024-25-panini-flawless-basketball-hobby-box', 2024, 'Panini', 'NBA', 'Flawless', 'Hobby Box', '2025-02-15', '2024-25 Panini Flawless NBA Hobby Box.', '/products/2024-25-panini-flawless-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2024-25-panini-hoops-basketball-hobby-box', 2024, 'Panini', 'NBA', 'Hoops', 'Hobby Box', '2025-02-15', '2024-25 Panini Hoops NBA Hobby Box.', '/products/2024-25-panini-hoops-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-bowman-best-basketball-hobby-box', 2025, 'Topps', 'NBA', 'Bowman Best', 'Hobby Box', '2026-02-15', '2025-26 Topps Bowman Best NBA Hobby Box.', '/products/2025-26-topps-bowman-best-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-bowman-u-basketball-hobby-box', 2025, 'Topps', 'NBA', 'Bowman U', 'Hobby Box', '2026-02-15', '2025-26 Topps Bowman U NBA Hobby Box.', '/products/2025-26-topps-bowman-u-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-chrome-basketball-blaster-box', 2025, 'Topps', 'NBA', 'Chrome', 'Blaster Box', '2026-02-15', '2025-26 Topps Chrome NBA Blaster Box.', '/products/2025-26-topps-chrome-basketball-blaster-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-chrome-basketball-fotl-hobby-box', 2025, 'Topps', 'NBA', 'Chrome', 'FOTL Hobby Box', '2026-02-15', '2025-26 Topps Chrome NBA FOTL Hobby Box.', '/products/2025-26-topps-chrome-basketball-fotl-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-chrome-basketball-hanger-box', 2025, 'Topps', 'NBA', 'Chrome', 'Hanger Box', '2026-02-15', '2025-26 Topps Chrome NBA Hanger Box.', '/products/2025-26-topps-chrome-basketball-hanger-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-chrome-basketball-hobby-box', 2025, 'Topps', 'NBA', 'Chrome', 'Hobby Box', '2026-02-15', '2025-26 Topps Chrome NBA Hobby Box.', '/products/2025-26-topps-chrome-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-chrome-basketball-jumbo-box', 2025, 'Topps', 'NBA', 'Chrome', 'Jumbo Box', '2026-02-15', '2025-26 Topps Chrome NBA Jumbo Box.', '/products/2025-26-topps-chrome-basketball-jumbo-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-chrome-basketball-mega-box', 2025, 'Topps', 'NBA', 'Chrome', 'Mega Box', '2026-02-15', '2025-26 Topps Chrome NBA Mega Box.', '/products/2025-26-topps-chrome-basketball-mega-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-chrome-basketball-value-box', 2025, 'Topps', 'NBA', 'Chrome', 'Value Box', '2026-02-15', '2025-26 Topps Chrome NBA Value Box.', '/products/2025-26-topps-chrome-basketball-value-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-chrome-sapphire-edition-basketball-hobby-box', 2025, 'Topps', 'NBA', 'Chrome Sapphire Edition', 'Hobby Box', '2026-02-15', '2025-26 Topps Chrome Sapphire Edition NBA Hobby Box.', '/products/2025-26-topps-chrome-sapphire-edition-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-finest-basketball-hobby-box', 2025, 'Topps', 'NBA', 'Finest', 'Hobby Box', '2026-02-15', '2025-26 Topps Finest NBA Hobby Box.', '/products/2025-26-topps-finest-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-26-topps-inception-basketball-hobby-box', 2025, 'Topps', 'NBA', 'Inception', 'Hobby Box', '2026-02-15', '2025-26 Topps Inception NBA Hobby Box.', '/products/2025-26-topps-inception-basketball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-bowman-baseball-mega-box', 2025, 'Bowman', 'MLB', 'Bowman', 'Mega Box', '2025-07-15', '2025 Bowman MLB Mega Box.', '/products/2025-bowman-baseball-mega-box.jpg', '#475569', '#0f172a'),
  ('2025-bowman-chrome-baseball-hobby-box', 2025, 'Bowman', 'MLB', 'Bowman Chrome', 'Hobby Box', '2025-07-15', '2025 Bowman Chrome MLB Hobby Box.', '/products/2025-bowman-chrome-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-panini-donruss-football-mega-box', 2025, 'Panini', 'NFL', 'Donruss', 'Mega Box', '2025-10-15', '2025 Panini Donruss NFL Mega Box.', '/products/2025-panini-donruss-football-mega-box.jpg', '#475569', '#0f172a'),
  ('2025-panini-prizm-football-blaster-box', 2025, 'Panini', 'NFL', 'Prizm', 'Blaster Box', '2025-10-15', '2025 Panini Prizm NFL Blaster Box.', '/products/2025-panini-prizm-football-blaster-box.jpg', '#475569', '#0f172a'),
  ('2025-panini-prizm-football-hanger-box', 2025, 'Panini', 'NFL', 'Prizm', 'Hanger Box', '2025-10-15', '2025 Panini Prizm NFL Hanger Box.', '/products/2025-panini-prizm-football-hanger-box.jpg', '#475569', '#0f172a'),
  ('2025-panini-prizm-football-mega-box', 2025, 'Panini', 'NFL', 'Prizm', 'Mega Box', '2025-10-15', '2025 Panini Prizm NFL Mega Box.', '/products/2025-panini-prizm-football-mega-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-baseball-hobby-box', 2025, 'Topps', 'MLB', 'Chrome', 'Hobby Box', '2025-07-15', '2025 Topps Chrome MLB Hobby Box.', '/products/2025-topps-chrome-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-football-blaster-box', 2025, 'Topps', 'NFL', 'Chrome', 'Blaster Box', '2025-10-15', '2025 Topps Chrome NFL Blaster Box.', '/products/2025-topps-chrome-football-blaster-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-football-fotl-hobby-box', 2025, 'Topps', 'NFL', 'Chrome', 'FOTL Hobby Box', '2025-10-15', '2025 Topps Chrome NFL FOTL Hobby Box.', '/products/2025-topps-chrome-football-fotl-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-football-hanger-box', 2025, 'Topps', 'NFL', 'Chrome', 'Hanger Box', '2025-10-15', '2025 Topps Chrome NFL Hanger Box.', '/products/2025-topps-chrome-football-hanger-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-football-hobby-box', 2025, 'Topps', 'NFL', 'Chrome', 'Hobby Box', '2025-10-15', '2025 Topps Chrome NFL Hobby Box.', '/products/2025-topps-chrome-football-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-football-jumbo-box', 2025, 'Topps', 'NFL', 'Chrome', 'Jumbo Box', '2025-10-15', '2025 Topps Chrome NFL Jumbo Box.', '/products/2025-topps-chrome-football-jumbo-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-football-mega-box', 2025, 'Topps', 'NFL', 'Chrome', 'Mega Box', '2025-10-15', '2025 Topps Chrome NFL Mega Box.', '/products/2025-topps-chrome-football-mega-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-football-value-box', 2025, 'Topps', 'NFL', 'Chrome', 'Value Box', '2025-10-15', '2025 Topps Chrome NFL Value Box.', '/products/2025-topps-chrome-football-value-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-chrome-sapphire-edition-baseball-hobby-box', 2025, 'Topps', 'MLB', 'Chrome Sapphire Edition', 'Hobby Box', '2025-07-15', '2025 Topps Chrome Sapphire Edition MLB Hobby Box.', '/products/2025-topps-chrome-sapphire-edition-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-five-star-baseball-hobby-box', 2025, 'Topps', 'MLB', 'Five Star', 'Hobby Box', '2025-07-15', '2025 Topps Five Star MLB Hobby Box.', '/products/2025-topps-five-star-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-holiday-baseball-mega-box', 2025, 'Topps', 'MLB', 'Holiday', 'Mega Box', '2025-07-15', '2025 Topps Holiday MLB Mega Box.', '/products/2025-topps-holiday-baseball-mega-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-pristine-baseball-hobby-box', 2025, 'Topps', 'MLB', 'Pristine', 'Hobby Box', '2025-07-15', '2025 Topps Pristine MLB Hobby Box.', '/products/2025-topps-pristine-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-series-2-baseball-hobby-box', 2025, 'Topps', 'MLB', 'Series 2', 'Hobby Box', '2025-07-15', '2025 Topps Series 2 MLB Hobby Box.', '/products/2025-topps-series-2-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-stadium-club-baseball-hobby-box', 2025, 'Topps', 'MLB', 'Stadium Club', 'Hobby Box', '2025-07-15', '2025 Topps Stadium Club MLB Hobby Box.', '/products/2025-topps-stadium-club-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-sterling-baseball-hobby-box', 2025, 'Topps', 'MLB', 'Sterling', 'Hobby Box', '2025-07-15', '2025 Topps Sterling MLB Hobby Box.', '/products/2025-topps-sterling-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2025-topps-tribute-baseball-hobby-box', 2025, 'Topps', 'MLB', 'Tribute', 'Hobby Box', '2025-07-15', '2025 Topps Tribute MLB Hobby Box.', '/products/2025-topps-tribute-baseball-hobby-box.jpg', '#475569', '#0f172a'),
  ('2026-topps-chrome-black-baseball-hobby-box', 2026, 'Topps', 'MLB', 'Chrome Black', 'Hobby Box', '2026-07-15', '2026 Topps Chrome Black MLB Hobby Box.', '/products/2026-topps-chrome-black-baseball-hobby-box.jpg', '#475569', '#0f172a')
on conflict (slug) do nothing;
