-- 0032_soccer_launch_catalog.sql
-- Soccer launch catalog: top-traded sealed soccer products across the
-- two main licensors (Topps and Panini). Modern era (2023-2025).
--
-- Topps owns most major club competitions (UEFA Club Competitions,
-- MLS, Bundesliga, Premier League, La Liga). Panini holds World Cup
-- and EURO international tournaments + a few league licenses.
--
-- Variants ship as Hobby Box (the flagship), often Mega/Blaster/Hanger
-- in retail. Cases auto-generated by migration 0030's pattern (run
-- the standard "-box -> -case" backfill SQL after this).
--
-- Slug pattern: <year>-<brand>-<set-with-soccer-suffix>-soccer-<product>
-- Soccer in this market uses season notation ("2024-25") similar to
-- NBA/NHL since the European/MLS season spans years.
--
-- All published. image_url null until admin uploads.
-- Idempotent: ON CONFLICT (slug) DO NOTHING.
-- Requires migration 0031 (Soccer enum value) to be applied first.

insert into skus (
  slug, year, brand, sport, set_name, product, release_date,
  description, image_url, gradient_from, gradient_to, is_published
)
values
  -- ===========================================================================
  -- Topps Chrome UEFA Club Competitions — the flagship soccer hobby release
  -- ===========================================================================

  ('2023-24-topps-chrome-uefa-club-competitions-soccer-hobby-box', 2023, 'Topps', 'Soccer', 'Chrome UEFA Club Competitions', 'Hobby Box', '2024-04-17',
    '2023-24 Topps Chrome UEFA Club Competitions Hobby Box. Champions League, Europa League, Europa Conference League. 18 packs per box, 1 auto + Refractor parallels.',
    null, '#0ea5e9', '#1e3a8a', true),

  ('2024-25-topps-chrome-uefa-club-competitions-soccer-hobby-box', 2024, 'Topps', 'Soccer', 'Chrome UEFA Club Competitions', 'Hobby Box', '2025-05-21',
    '2024-25 Topps Chrome UEFA Club Competitions Hobby Box. The flagship soccer hobby release. Mbappé Real Madrid, Yamal, Bellingham. 18 packs per box.',
    null, '#0ea5e9', '#1e3a8a', true),

  ('2024-25-topps-chrome-uefa-club-competitions-soccer-mega-box', 2024, 'Topps', 'Soccer', 'Chrome UEFA Club Competitions', 'Mega Box', '2025-05-21',
    '2024-25 Topps Chrome UEFA Mega Box. Retail-exclusive parallels.',
    null, '#0ea5e9', '#1e3a8a', true),

  -- ===========================================================================
  -- Topps Chrome Sapphire / X-Fractor UEFA — collector chase
  -- ===========================================================================

  ('2024-25-topps-chrome-sapphire-edition-uefa-club-competitions-soccer-hobby-box', 2024, 'Topps', 'Soccer', 'Chrome Sapphire Edition UEFA Club Competitions', 'Hobby Box', '2025-08-13',
    '2024-25 Topps Chrome Sapphire Edition UEFA Hobby Box. Online-exclusive sapphire refractor parallels of every base card.',
    null, '#1e3a8a', '#06b6d4', true),

  -- ===========================================================================
  -- Topps Finest UEFA Club Competitions — premium chrome
  -- ===========================================================================

  ('2023-24-topps-finest-uefa-club-competitions-soccer-hobby-box', 2023, 'Topps', 'Soccer', 'Finest UEFA Club Competitions', 'Hobby Box', '2024-09-04',
    '2023-24 Topps Finest UEFA Club Competitions Hobby Box. Premium chrome, 2 mini boxes per master, 2 autos per box.',
    null, '#1e3a8a', '#fbbf24', true),

  ('2024-25-topps-finest-uefa-club-competitions-soccer-hobby-box', 2024, 'Topps', 'Soccer', 'Finest UEFA Club Competitions', 'Hobby Box', '2025-09-10',
    '2024-25 Topps Finest UEFA Club Competitions Hobby Box. Premium chrome refractors, 2 autos per box.',
    null, '#1e3a8a', '#fbbf24', true),

  -- ===========================================================================
  -- Topps Stadium Club Chrome UEFA — photography-focused chrome
  -- ===========================================================================

  ('2024-25-topps-stadium-club-chrome-uefa-club-competitions-soccer-hobby-box', 2024, 'Topps', 'Soccer', 'Stadium Club Chrome UEFA Club Competitions', 'Hobby Box', '2025-10-15',
    '2024-25 Topps Stadium Club Chrome UEFA Hobby Box. Iconic photography on chrome stock.',
    null, '#0c4a6e', '#fbbf24', true),

  -- ===========================================================================
  -- Topps MLS — Major League Soccer flagship
  -- ===========================================================================

  ('2024-topps-chrome-mls-soccer-hobby-box', 2024, 'Topps', 'Soccer', 'Chrome MLS', 'Hobby Box', '2024-11-13',
    '2024 Topps Chrome MLS Hobby Box. Messi Inter Miami era, Apple TV-driven product. 18 packs per box, 1 auto.',
    null, '#dc2626', '#0ea5e9', true),

  ('2025-topps-chrome-mls-soccer-hobby-box', 2025, 'Topps', 'Soccer', 'Chrome MLS', 'Hobby Box', '2025-11-12',
    '2025 Topps Chrome MLS Hobby Box. Messi, Suárez, Insigne. The flagship MLS hobby product.',
    null, '#dc2626', '#0ea5e9', true),

  -- ===========================================================================
  -- Topps Bundesliga / Premier League — domestic-league chrome
  -- ===========================================================================

  ('2024-25-topps-chrome-bundesliga-soccer-hobby-box', 2024, 'Topps', 'Soccer', 'Chrome Bundesliga', 'Hobby Box', '2025-06-04',
    '2024-25 Topps Chrome Bundesliga Hobby Box. Bayern, Dortmund, Leverkusen. 18 packs, 1 auto per box.',
    null, '#1f2937', '#dc2626', true),

  ('2024-25-topps-chrome-premier-league-soccer-hobby-box', 2024, 'Topps', 'Soccer', 'Chrome Premier League', 'Hobby Box', '2025-08-27',
    '2024-25 Topps Chrome Premier League Hobby Box. Haaland, Salah, Saka, Palmer. The flagship PL hobby release.',
    null, '#7c3aed', '#facc15', true),

  -- ===========================================================================
  -- Panini Donruss / Mosaic Premier League — alternative PL chase
  -- ===========================================================================

  ('2023-24-panini-donruss-premier-league-soccer-hobby-box', 2023, 'Panini', 'Soccer', 'Donruss Premier League', 'Hobby Box', '2024-07-31',
    '2023-24 Panini Donruss Premier League Hobby Box. Rated Rookies, Optic Press Proofs. 24 packs per box.',
    null, '#9a3412', '#fbbf24', true),

  ('2023-24-panini-mosaic-premier-league-soccer-hobby-box', 2023, 'Panini', 'Soccer', 'Mosaic Premier League', 'Hobby Box', '2024-08-21',
    '2023-24 Panini Mosaic Premier League Hobby Box. Vibrant prizm-style parallels.',
    null, '#7f1d1d', '#0ea5e9', true),

  -- ===========================================================================
  -- Panini Prizm World Cup — international tournament chase
  -- ===========================================================================

  ('2022-panini-prizm-world-cup-soccer-hobby-box', 2022, 'Panini', 'Soccer', 'Prizm World Cup', 'Hobby Box', '2022-11-09',
    '2022 Panini Prizm World Cup Hobby Box. Qatar 2022. Mbappé, Messi, Bellingham first-ever Prizm WC. 12 packs per box. The most-traded modern soccer set.',
    null, '#1e40af', '#a855f7', true)

on conflict (slug) do nothing;
