-- 0055_bind_image_files_to_skus.sql
-- Generic image-binding sweep. For every SKU row whose slug matches an
-- image file already saved in /public/products/, set image_url to that
-- file's path. Many product photos exist on disk but their DB rows
-- still have image_url=null (because the SKU was added before the
-- image, or the file was added without updating the row). The result
-- is a gradient fallback instead of the real photo even though the
-- image is right there.
--
-- This UPDATE is conservative: it only fills NULL image_url values,
-- never overwrites an explicit binding. So if a row was already
-- pointed at a different image (e.g. a sibling-variant fallback), it
-- won't get clobbered.
--
-- The expected slug→file convention is:
--   /products/<slug>.jpg
-- where <slug> is exactly the SKU's slug. Anything that doesn't match
-- this pattern stays null and uses the gradient fallback.

-- Bind each known-on-disk image to its SKU row. List generated by
-- enumerating /public/products/*.jpg and mapping each filename back
-- to the matching slug. Adding files outside this list later requires
-- either re-running this with a refreshed list, or a manual UPDATE.

update skus
  set image_url = '/products/' || slug || '.jpg'
  where image_url is null
    and slug in (
      '2025-26-panini-donruss-basketball-hobby-box',
      '2025-26-panini-national-treasures-road-to-fifa-world-cup-soccer-hobby-box',
      '2025-26-panini-noir-basketball-hobby-box',
      '2025-26-panini-noir-road-to-fifa-world-cup-soccer-hobby-box',
      '2025-26-panini-prizm-basketball-fotl-hobby-box',
      '2025-26-panini-prizm-basketball-hobby-box',
      '2025-26-panini-prizm-fifa-soccer-hobby-box',
      '2025-26-panini-select-road-to-fifa-world-cup-soccer-hobby-box',
      '2025-26-panini-signature-series-basketball-hobby-box',
      '2025-26-topps-basketball-hobby-box',
      '2025-26-topps-bowman-basketball-hobby-box',
      '2025-26-topps-bowman-u-basketball-hobby-box',
      '2025-26-topps-chrome-basketball-blaster-box',
      '2025-26-topps-chrome-basketball-first-day-issue-hobby-box',
      '2025-26-topps-chrome-basketball-hanger-box',
      '2025-26-topps-chrome-basketball-hobby-box',
      '2025-26-topps-chrome-basketball-jumbo-box',
      '2025-26-topps-chrome-basketball-mega-box',
      '2025-26-topps-chrome-premier-league-soccer-hobby-box',
      '2025-26-topps-chrome-sapphire-edition-basketball-hobby-box',
      '2025-26-topps-chrome-uefa-club-competitions-soccer-hobby-box',
      '2025-26-topps-chrome-uefa-club-competitions-soccer-hobby-case',
      '2025-26-topps-chrome-uefa-club-competitions-soccer-mega-box',
      '2025-26-topps-cosmic-chrome-basketball-hobby-box',
      '2025-26-topps-finest-basketball-hobby-box',
      '2025-26-topps-nba-hoops-basketball-hobby-box',
      '2025-26-topps-signature-class-basketball-hobby-box',
      '2025-26-upper-deck-black-diamond-hockey-hobby-box',
      '2025-26-upper-deck-chl-hockey-hobby-box',
      '2025-26-upper-deck-extended-series-hockey-hobby-box',
      '2025-26-upper-deck-series-1-hockey-hobby-box',
      '2025-26-upper-deck-series-2-hockey-hobby-box',
      '2025-26-upper-deck-sp-authentic-hockey-hobby-box',
      '2025-26-upper-deck-sp-game-used-chl-hockey-hobby-box',
      '2025-26-upper-deck-spx-hockey-hobby-box',
      '2025-bowman-baseball-hobby-jumbo-box',
      '2025-bowman-baseball-mega-box',
      '2025-bowman-chrome-baseball-hobby-box',
      '2025-bowman-platinum-baseball-hobby-box',
      '2025-panini-certified-football-hobby-box',
      '2025-panini-donruss-football-hobby-box',
      '2025-panini-donruss-football-mega-box',
      '2025-panini-donruss-optic-football-hobby-box',
      '2025-panini-flawless-football-hobby-box',
      '2025-panini-honors-football-hobby-box',
      '2025-panini-immaculate-football-hobby-box',
      '2025-panini-mosaic-football-hobby-box',
      '2025-panini-national-treasures-football-hobby-box',
      '2025-panini-phoenix-football-hobby-box',
      '2025-panini-prizm-football-blaster-box',
      '2025-panini-prizm-football-fotl-hobby-box',
      '2025-panini-prizm-football-hanger-box',
      '2025-panini-prizm-football-hobby-box',
      '2025-panini-prizm-football-mega-box',
      '2025-panini-select-football-hobby-box',
      '2025-topps-allen-and-ginter-baseball-hobby-box',
      '2025-topps-basketball-hobby-box',
      '2025-topps-chrome-baseball-hobby-box',
      '2025-topps-chrome-football-blaster-box',
      '2025-topps-chrome-football-first-day-issue-hobby-box',
      '2025-topps-chrome-football-hanger-box',
      '2025-topps-chrome-football-hobby-box',
      '2025-topps-chrome-football-jumbo-box',
      '2025-topps-chrome-football-mega-box',
      '2025-topps-chrome-mls-soccer-hobby-box',
      '2025-topps-chrome-platinum-baseball-hobby-box',
      '2025-topps-chrome-sapphire-edition-baseball-hobby-box',
      '2025-topps-chrome-update-baseball-hobby-box',
      '2025-topps-finest-football-hobby-box',
      '2025-topps-five-star-baseball-hobby-box',
      '2025-topps-heritage-baseball-hobby-box',
      '2025-topps-holiday-baseball-mega-box',
      '2025-topps-pristine-baseball-hobby-box',
      '2025-topps-series-1-baseball-hobby-box',
      '2025-topps-series-2-baseball-hobby-box',
      '2025-topps-signature-class-football-hobby-box',
      '2025-topps-stadium-club-baseball-hobby-box',
      '2025-topps-sterling-baseball-hobby-box',
      '2025-topps-tier-one-baseball-hobby-box',
      '2025-topps-tribute-baseball-hobby-box',
      '2025-topps-update-baseball-hobby-box'
    );
